use crate::protocol::traits::Identify;

pub enum Packet {
    AddEntity,
    AddExperienceOrb,
    Animate,
    AwardStats,
    BlockChangedAck,
    BlockDestruction,
    BlockEntityData,
    BlockEvent,
    BlockUpdate,
    BossEvent,
    BundleDelimiter,
    ChangeDifficulty,
    ChunkBatchFinished,
    ChunkBatchStart,
    ChunksBiomes,
    ClearTitles,
    CommandSuggestions,
    Commands,
    ContainerClose,
    ContainerSetContent,
    ContainerSetData,
    ContainerSetSlot,
    CookieRequest,
    Cooldown,
    CustomChatCompletions,
    CustomPayload,
    CustomReportDetails,
    DamageEvent,
    DebugSample,
    DeleteChat,
    Disconnect,
    DisguisedChat,
    EntityEvent,
    Explode,
    ForgetLevelChunk,
    GameEvent,
    HorseScreenOpen,
    HurtAnimation,
    InitializeBorder,
    KeepAlive,
    LevelChunkWithLight,
    LevelEvent,
    LevelParticles,
    LightUpdate,
    Login,
    MapItemData,
    MerchantOffers,
    MoveEntityPos,
    MoveEntityPosRot,
    MoveEntityRot,
    MoveVehicle,
    OpenBook,
    OpenScreen,
    OpenSignEditor,
    Ping,
    PlaceGhostRecipe,
    PlayerAbilities,
    PlayerChat,
    PlayerCombatEnd,
    PlayerCombatEnter,
    PlayerCombatKill,
    PlayerInfoRemove,
    PlayerInfoUpdate,
    PlayerLookAt,
    PlayerPosition,
    PongResponse,
    ProjectilePower,
    Recipe,
    RemoveEntities,
    RemoveMobEffect,
    ResetScore,
    ResourcePackPop,
    ResourcePackPush,
    Respawn,
    RotateHead,
    SectionBlocksUpdate,
    SelectAdvancementsTab,
    ServerData,
    ServerLinks,
    SetActionBarText,
    SetBorderCenter,
    SetBorderLerpSize,
    SetBorderSize,
    SetBorderWarningDelay,
    SetBorderWarningDistance,
    SetCamera,
    SetCarriedItem,
    SetChunkCacheCenter,
    SetChunkCacheRadius,
    SetDefaultSpawnPosition,
    SetDisplayObjective,
    SetEntityData,
    SetEntityLink,
    SetEntityMotion,
    SetEquipment,
    SetExperience,
    SetHealth,
    SetObjective,
    SetPassengers,
    SetPlayerTeam,
    SetScore,
    SetSimulationDistance,
    SetSubtitleText,
    SetTime,
    SetTitleText,
    SetTitlesAnimation,
    Sound,
    SoundEntity,
    StartConfiguration,
    StopSound,
    StoreCookie,
    SystemChat,
    TabList,
    TagQuery,
    TakeItemEntity,
    TeleportEntity,
    TickingState,
    TickingStep,
    Transfer,
    UpdateAdvancements,
    UpdateAttributes,
    UpdateMobEffect,
    UpdateRecipes,
    UpdateTags,
}

impl Identify for Packet {
    fn get_id(&self) -> u8 {
        match self {
            Packet::AddEntity => 1,
            Packet::AddExperienceOrb => 2,
            Packet::Animate => 3,
            Packet::AwardStats => 4,
            Packet::BlockChangedAck => 5,
            Packet::BlockDestruction => 6,
            Packet::BlockEntityData => 7,
            Packet::BlockEvent => 8,
            Packet::BlockUpdate => 9,
            Packet::BossEvent => 10,
            Packet::BundleDelimiter => 0,
            Packet::ChangeDifficulty => 11,
            Packet::ChunkBatchFinished => 12,
            Packet::ChunkBatchStart => 13,
            Packet::ChunksBiomes => 14,
            Packet::ClearTitles => 15,
            Packet::CommandSuggestions => 16,
            Packet::Commands => 17,
            Packet::ContainerClose => 18,
            Packet::ContainerSetContent => 19,
            Packet::ContainerSetData => 20,
            Packet::ContainerSetSlot => 21,
            Packet::CookieRequest => 22,
            Packet::Cooldown => 23,
            Packet::CustomChatCompletions => 24,
            Packet::CustomPayload => 25,
            Packet::CustomReportDetails => 122,
            Packet::DamageEvent => 26,
            Packet::DebugSample => 27,
            Packet::DeleteChat => 28,
            Packet::Disconnect => 29,
            Packet::DisguisedChat => 30,
            Packet::EntityEvent => 31,
            Packet::Explode => 32,
            Packet::ForgetLevelChunk => 33,
            Packet::GameEvent => 34,
            Packet::HorseScreenOpen => 35,
            Packet::HurtAnimation => 36,
            Packet::InitializeBorder => 37,
            Packet::KeepAlive => 38,
            Packet::LevelChunkWithLight => 39,
            Packet::LevelEvent => 40,
            Packet::LevelParticles => 41,
            Packet::LightUpdate => 42,
            Packet::Login => 43,
            Packet::MapItemData => 44,
            Packet::MerchantOffers => 45,
            Packet::MoveEntityPos => 46,
            Packet::MoveEntityPosRot => 47,
            Packet::MoveEntityRot => 48,
            Packet::MoveVehicle => 49,
            Packet::OpenBook => 50,
            Packet::OpenScreen => 51,
            Packet::OpenSignEditor => 52,
            Packet::Ping => 53,
            Packet::PlaceGhostRecipe => 55,
            Packet::PlayerAbilities => 56,
            Packet::PlayerChat => 57,
            Packet::PlayerCombatEnd => 58,
            Packet::PlayerCombatEnter => 59,
            Packet::PlayerCombatKill => 60,
            Packet::PlayerInfoRemove => 61,
            Packet::PlayerInfoUpdate => 62,
            Packet::PlayerLookAt => 63,
            Packet::PlayerPosition => 64,
            Packet::PongResponse => 54,
            Packet::ProjectilePower => 121,
            Packet::Recipe => 65,
            Packet::RemoveEntities => 66,
            Packet::RemoveMobEffect => 67,
            Packet::ResetScore => 68,
            Packet::ResourcePackPop => 69,
            Packet::ResourcePackPush => 70,
            Packet::Respawn => 71,
            Packet::RotateHead => 72,
            Packet::SectionBlocksUpdate => 73,
            Packet::SelectAdvancementsTab => 74,
            Packet::ServerData => 75,
            Packet::ServerLinks => 123,
            Packet::SetActionBarText => 76,
            Packet::SetBorderCenter => 77,
            Packet::SetBorderLerpSize => 78,
            Packet::SetBorderSize => 79,
            Packet::SetBorderWarningDelay => 80,
            Packet::SetBorderWarningDistance => 81,
            Packet::SetCamera => 82,
            Packet::SetCarriedItem => 83,
            Packet::SetChunkCacheCenter => 84,
            Packet::SetChunkCacheRadius => 85,
            Packet::SetDefaultSpawnPosition => 86,
            Packet::SetDisplayObjective => 87,
            Packet::SetEntityData => 88,
            Packet::SetEntityLink => 89,
            Packet::SetEntityMotion => 90,
            Packet::SetEquipment => 91,
            Packet::SetExperience => 92,
            Packet::SetHealth => 93,
            Packet::SetObjective => 94,
            Packet::SetPassengers => 95,
            Packet::SetPlayerTeam => 96,
            Packet::SetScore => 97,
            Packet::SetSimulationDistance => 98,
            Packet::SetSubtitleText => 99,
            Packet::SetTime => 100,
            Packet::SetTitleText => 101,
            Packet::SetTitlesAnimation => 102,
            Packet::Sound => 104,
            Packet::SoundEntity => 103,
            Packet::StartConfiguration => 105,
            Packet::StopSound => 106,
            Packet::StoreCookie => 107,
            Packet::SystemChat => 108,
            Packet::TabList => 109,
            Packet::TagQuery => 110,
            Packet::TakeItemEntity => 111,
            Packet::TeleportEntity => 112,
            Packet::TickingState => 113,
            Packet::TickingStep => 114,
            Packet::Transfer => 115,
            Packet::UpdateAdvancements => 116,
            Packet::UpdateAttributes => 117,
            Packet::UpdateMobEffect => 118,
            Packet::UpdateRecipes => 119,
            Packet::UpdateTags => 120,
        }
    }
}
