[package]
name = "blink_macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
byteorder = "1.5.0"
proc-macro2 = "1.0.83"
quote = "1.0.36"
syn = "2.0.65"
flate2.workspace = true
